### ISSUE TITLE
"Stabilizable" prototype for expanded const generics

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#100]
| Metadata      | |
| --------      | --- |
| Owner(s)      | @BoxyUwU |
| Team(s)       | [lang](http://github.com/rust-lang/lang-team), [types](https://github.com/rust-lang/types-team) |
| Goal document | [2024h2/min_generic_const_arguments](https://rust-lang.github.io/rust-project-goals/2024h2/min_generic_const_arguments.html) |

## Summary

Experiment with a new `min_generic_const_args` implementation to address challenges found with the existing approach

## Tasks and status

* [ ] Discussion and moral support ([lang](http://github.com/rust-lang/lang-team), [types](https://github.com/rust-lang/types-team) ![Team][])
* [ ] Implementation and mentoring (@BoxyUwu)
* [ ] Implementation (@camelid)
* [ ] Reviewer (@compiler-errors)

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.

**Comment by BoxyUwU** [comment]
Key Developments: #125915 landed which is necessary to start implementation work on `min_generic_const_args`, a draft outlining the ideas behind the proposed feature has also been written
Blockers: no
Help Wanted: no

**Comment by BoxyUwU** [comment]
The past ~month has been spent figuring out some implementation constraints arising from DefId creation of anon consts. My time has also been somewhat diverted to other things though that should have cleared up now :-)

**Comment by BoxyUwU** [comment]
camlid has started working on using the new lowering schema for more than just const parameters which once done will allow us to introduce a `min_generic_const_args` feature gate

**Comment by BoxyUwU** [comment]
`min_generic_const_args` now exists as a feature gate (though without any functionality only some gated refactorings), shouldn't be long before it has actual functionality behind it 🤞 The refactoring to remove all the `eval_x` methods on `ty::Const` has been completed so it will now be possible to correctly implement normalization for constants.

**Comment by BoxyUwU** [comment]
(nothing this month)

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h1

**Comment by BoxyUwU** [comment]
camelid has a PR up which is ~fully finished + reviewed which enables resolving and lowering all paths under `min_generic_const_args`. It's taken a while to get this bit finished as we had to take care not to make parts of the compiler unmaintainable by duplicating all the logic for type and const path lowering.

**Comment by BoxyUwU** [comment]
camelids PR has been merged, we now correctly (to the best of my knowledge) lower const paths under mgca. I have a PR open to ensure that we handle evaluation of paths to consts with generics or inference variables correctly, and that we do not attempt to evaluate constants before they have been checked to be well formed. I'm also currently mentoring someone to implement proper handling of normalization of inherent associated constants under mgca.

**Comment by BoxyUwU** [comment]
I've a PR open to make resolving inherent assoc terms in item signatures not result in query cycles, this will be necessary for uses of inherent assoc consts in the type system under mgca. camelid is currently working on representing const items as aliases to type system consts rather than bodies like they currently are, this is necessary to implement normalization of const const aliases under mgca, it will also allow us to implement the core mgca check of const aliases in the type system being equal to valid const arguments, and also we'll be able to split out a full gca feature gate *without* that restriction.

The PR mentioned in the previous update to handle const aliases with inference variables correctly has turned into a bit of a rabbit hole. It turned out that there were *stable* issues around const evaluation and illformed constants resulting in ICEs so I've wound up trying to get those fixed and have been writing up a document explaining justification for a breaking change there.

**Comment by BoxyUwU** [comment]
We should now be correctly deferring evaluation of type system constants making use of generic parameters or inference variables. There's also been some work to make our normalization infrastructure more term agnostic (i.e. work on both types and consts). Camelid's PR mentioned in the previous update has also made great progress.

**Comment by BoxyUwU** [comment]
Not much to say since the last update- I have been focused on other areas of const generics and I believe camelid has been relatively busy with other things too. I intend for the next const generics project goal to be more broadly scoped than just `min_generic_const_args` so that other const generics work can be given a summary here :)

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by BoxyUwU** [comment]
Once again most progress here has been on `min_generic_const_args`.

@camelid's PR (rust-lang/rust#139558)  has now landed, as well as an additional PR of his: rust-lang/rust#148716. Between the two of these the core impl should be "mostly done" now, atleast with no additional feature gates enabled :).

The next big step is to make the `min_generic_const_args` prototype work well with `adt_const_params` which I've implemented myself in rust-lang/rust#149136 and rust-lang/rust#149114. These PRs still need to be reviewed but the bulk of the impl work there is now done. These PRs allow for constructing ADTs where the field values may themselves be const parameters or non-concrete uses of `type_const`s (ie the values are const argument positions).

Once my PRs have landed I would consider mgca as a *prototype* to be truly "done" though not done as an actual feature. Huge thanks to camelid for sticking through a bunch of fairly painful PRs to get us to this point.

**Comment by BoxyUwU** [comment]
Late on the update :') niko and i continue to meet to discuss const generics. we've made some progress on figuring out problems around privacy/safety in const generics. we've also been discussing the big picture stuff for const generics and where we're "heading".

**Comment by BoxyUwU** [comment]
started running weekly meetings about const generics to make it easier to keep up to date with all the people who are working on const generics stuff. i think min_adt_const_params is now at the point of what the RFC is going to specify.

GCA is making good progress thanks to ashley's work. i also met with lcnr where we talked about whether there was some version of mGCA that is stabilizeable in the near future or not (maybe!)

**Comment by tomassedovic** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2026

**Comment by BoxyUwU** [comment]
I've made a graph outlining a bunch of the stuff we're working towards with const generics and what it'll take to get there: https://raw.githubusercontent.com/rust-lang/project-const-generics/refs/heads/master/roadmap.svg most nodes are tracked by issues on the project-const-generics repo

I intend to look into stabilizing arrays and tuples in const generics soon as they are entirely non-controversial and quite small. I also intend to look into just stabilizing C-like enums in const generics soon as they are similarly quite small and dont have any interesting questions. I still am intending to stabilize adt_const_params at some point but given there are some controversial questions about how to handle privacy I intend to do that after getting the other useful stuff done first.

mGCA/GCA are currently going quite well. @khyperia is looking into removing mGCA/GCA's requirement that anon consts be written as `const { ... }`. this should bring us a lot closer to them being vaguely stabilizable as they'll no longer be hugely breaking :3 it should also make migrating from `generic_const_exprs`  to `generic_const_args` a lot easier

We've also changed `generic_const_args` to not support generic anon consts anymore. Previously you could write `type const FOO<T> = const { size_of::<T>() }` now we forbid that and instead just support uses of const items in the type system, so `const FOO<T> = const { size_of::<T>() }` can be used.

I've been holding off on putting out blog posts about const generics until the above changes to mGCA/GCA are done and the features settle down a bit as I don't want the blog posts to become immediately outdated 😅 

Some of the changes @khyperia is working on for removing the `const { ... }` syntax requirement will also unblock experimenting with some form of "argument position const generics" feature, something that would allow `rustc_legacy_const_generics` to be a "real" feature. (e.g. `fn foo(const X: usize) -> [u8; X]`)

**Comment by BoxyUwU** [comment]
### generic_const_args stuff :3

@khyperia's PR (rust-lang/rust#158617) to no longer 1require explicit `const { ... }` blocks for the GCA features has now landed. this is a nice step towards having something stabilizable :3 we intend to do some further work in this area and make a version of the gca features which requires explicit syntax for the new expressions we accept (e.g. `Foo<direct_const_arg!(T::ASSOC)>`) which should avoid a lot of thorny questions around how to determine if a const argument is an anon const or if its directly represented.

I'm currently in the process of writing up a document about a lot of the syntax concerns/thoughts around mGCA/GCA/etc (https://hackmd.io/8NxVqeZeSYGLbzvw1Ey9rQ). Once this is done I'll move it off of hackmd and into the project-const-generics' repo's documents folder for it to live somewhere more accessible.

@khyperia and I have also discussed options for making `type const` fully obsolete under GCA. now that we no longer require explicit const blocks, some of the previous considerations that made type const useful under GCA are no longer the case and we can do other solutions. we're intending to look into whether we can apply the same "heuristic" for whether an expression is an anon const or directly represented, to the rhs of const items under GCA.

We're probably also going to look into replacing `type const` with an attribute again. We no longer need the syntax to let us parse the rhs of type consts differently from normal const items (thanks to ashley's work). If it turns out that GCA doesn't need type const at all then we'll also want to avoid stabilizing type const syntax at all because it might get obviated one day with future stabilizations :3

@bit-aloo has opened PRs fixing a couple GCA bugs: rust-lang/rust#158640 rust-lang/rust#158479

### adt_const_params

I've been feeling kinda meh about trying to stabilize a min_adt_const_params with somewhat jank privacy restrictions so instead I think I'm going to take a step back from that and try and stabilize something even more minimal. This'll probably be support for tuples/arrays, then also C-like enums (data-less variants).

These types meet the somewhat jank restrictions that I was originally thinking were needed, while also being much easier to explain to users and still being a useful stabilization :3

---

finally, i intend to start doing these weekly so it's easier to remember what has happened since the last update and so that they're less effort to do 😅 I may have missed some PRs in this update since it's been a while since the last one but hopefully that should happen less now :sparkles:

if I missed anyones PRs pls dm me on zulip and I'll amend this update :>

**Comment by BoxyUwU** [comment]
@khyperia has opened [#159058](https://github.com/rust-lang/rust/issues/159058) which splits out the "figure out if its an anon const or a direct cosnt arg" logic into a separate feature gate and other wise requires explicit syntax for when a const argument *isnt* an anon const. This should be something "more stabilizable" because the heuristic for whether to represent something as an anon const or not has backwards compatibility problems and is genereally quite subtle/weird.

ashley has also opened [#159596](https://github.com/rust-lang/rust/issues/159596) which is just a small cleanup to make us not need to parse the rhs of type consts differently than normal expression positions :3 

@bit-aloo has opened [#159506](https://github.com/rust-lang/rust/issues/159506) which adds support for dyn compatible associated constants to `generic_const_args`.

@BoxyUwU and @nikomatsakis met to talk over the WIP hackmd from the last update. we didn't reach any "conclusions" but it was still generally useful and I think I now have a good sense of where I want to go with that document and just need to find the time to finish it :>

**Comment by BoxyUwU** [comment]
@Dnreikronos' rust-lang/rust#158738 has landed fixing an ICE when enabling both GCE and -Znext-solver. they've also got a PR to make diagnostics better when a function call is interpretted as a direct const arg: rust-lang/rust#157513. theyve also fixed an ICE where lowering erroneous const args to `hir::ConstArgKind::Error` would result in DefIds not appearing in the HIR rust-lang/rust#159229

@khyperia's PRs from the last update have now been merged:  rust-lang/rust#159596 rust-lang/rust#159058

@bit-aloo fixed an ICE in mGCA when writing a path to a static item: rust-lang/rust#158479. their PR to fix an ICE when writing a path to a function has also been fixed rust-lang/rust#157962. this illuminated some previously unknown complexity around supporting function items in the type system where having function item types in function signatures currently causes computing wf requirements to recurse infinitely as `wf(fndef)` requires `wf(fnsig(fndef))` which may itself contain `fndef` 

@bb1yd has a PR open to support `Self` aliases in the types of const parameters: rust-lang/rust#157949. this is tricky because the self alias might resolve to something with generic parameters which would be illegal without `generic_const_parameter_types`, or it might have forward declared generic parameters which would be illegal even with `generic_const_parameter_types`

@IsaiahCoroama has improved diagnostics when using `generic_const_exprs` in conjunction with the `rustc_legacy_const_generics` feature rust-lang/rust#158981

**Comment by BoxyUwU** [comment]
@rcvalle added CFI support for `adt_const_params` types in rust-lang/rust#159632

@zedddie has opened rust-lang/rust#160237 which will check constants are well formed before evaluating them to avoid us running const eval illformed MIR bodies

@bit-aloo's PR rust-lang/rust#159506 has now been approved, adding support for dyn compatible traits with associated constants to GCA 

@khyperia is cleaning up a bunch of implementation jank in the GCA features: rust-lang/rust#160216

**Comment by BoxyUwU** [comment]
Ive been working on some blog posts explaining what the GCA features are as well as how to migrate code using GCE over to the new stuff. I'm hoping to get this done sooner rather than later with how close the new solver is getting to being stabilized and its lack of support for GCE.

GCA is currently mostly where we want it functionality wise except that we have yet to implement suppport for implementing associated constants as direct const args/type consts. Noone is currently working on this but ideally it should happen soon as I believe it's the last major thing that needs to happen for GCA to be "feature complete". I've written up some thoughts about how to go about implementing this: [#project-const-generics > implementing assoc consts as direct args](https://rust-lang.zulipchat.com/#narrow/channel/260443-project-const-generics/topic/implementing.20assoc.20consts.20as.20direct.20args/with/617794119). I would love if someone would be able to work on this (though it's somewhat time sensitive).

There's been a lot of work recently involving the trait solver's entry point to const eval. @zedddie's PR from the last update, and @bit-aloo has since opened rust-lang/rust#160526. This has prompted us to take a bit of a step back and think about how to better structure the way that the solver calls into const eval because it was incrementally getting more and more complex and harder and harder to read 😅 @zedddie is now working on cleaning that up and has opened rust-lang/rust#161418 for this.

@khyperia has done a bunch of cleanup work that was leftover after the initial implementation of macroless gca and the `direct_const_arg` macro: rust-lang/rust#160216

@bit-aloo has implemented proper checks that `{ _ }` arguments under GCA can't be inferred to types: rust-lang/rust#160984. they've also fixed some ICEs where we weren't normalizing the types of values returned by const eval: rust-lang/rust#160526

@sjwang05 has fixed an ICE in directly represented array expressions rust-lang/rust#158587

@TaKO8Ki has fixed an ICE in defaulted const generics when using GCE together with GCA: rust-lang/rust#159303

@zakrad added a regression test for a GCE issue rust-lang/rust#160751

**Comment by BoxyUwU** [comment]
We (const generics project group) have spent some time discussing some reworks to `min_generic_const_args` and `generic_const_args` ([#project-const-generics > talkies at last](https://rust-lang.zulipchat.com/#narrow/channel/260443-project-const-generics/topic/talkies.20at.20last/with/620616030)).

This was brought on by the change in requiring explicit syntax for new directly represented const arguments/items, as well as the desire for full GCA to be able to implement normal const items with directly represented right hand sides.

We intend to yeet `type const` syntax and replace it with a trait-assoc-const-definition site `#[always_gca]` attribute which enforces that the associated const is always implemented as `= gca!(...)` where `...` is the new constructs supported by the GCA features. 

The `min_generic_const_args` feature will then only support:
- uses of `#[always_gca]` associated consts in the type system
- inherent and free const items implemented as `= gca!(...)`
Whereas full `generic_const_args` will support any const item in the type system and allow implementing any associated constant as `= gca!(...)`.

@khyperia has implemented a first step towards this by supporting writing normal const items with `= direct!(...)` rust-lang/rust#162179. As part of implementing this she ran into a bunch of issues with inherent associated consts causing us to take a bit of a detour and improve support for them under the GCA features: rust-lang/rust#161929 rust-lang/rust#162173 rust-lang/rust#162168 rust-lang/rust#161858

One of @Dnreikronos's PRs from previous updates have since been merged: rust-lang/rust#157513 improving diagnostics when a function call is lowered as a direct const arg. Their PR rust-lang/rust#158874 has also been merged which fixes an ICE where we'd access the type of an anon const before it'd been lowered and fed :3

@bb1yd's PR to allow `Self` aliases in the types of const generics under `min_adt_const_params` has also landed: rust-lang/rust#157949

@YUZHEthefool has a PR to check that const items used in the type system are of types implementing `ConstParamTy`, this is necessary for `generic_const_args` which allows constants in the type system which did not have this checked at the definition site. rust-lang/rust#161131
