### ISSUE TITLE
Provided reasons for yanked crates

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#101]
| Metadata      | |
| --------      | --- |
| Owner(s)      | @Rustin170506  |
| Team(s)       | [cargo](https://github.com/rust-lang/cargo), [crates-io](https://github.com/rust-lang/crates.io) |
| Goal document | [2024h2/yank-crates-with-a-reason](https://rust-lang.github.io/rust-project-goals/2024h2/yank-crates-with-a-reason.html) |

## Summary

Over the next 6 months, we will add support to the registry yank API for providing a reason when a crate is yanked. This reason can then be displayed to users. After this feature has been up and running for a while, we'll open it up to Cargo to support filling in the reason for yanking.

## Tasks and status

* [ ] Yank crates with a reason
  * [x] Implementation (@Rustin170506)
  * [x] Standard reviews ([crates-io](https://github.com/rust-lang/crates.io) ![Team][])
  * [ ] Try it out in crates.io ([crates-io](https://github.com/rust-lang/crates.io) ![Team][])
  * [ ] Author RFC (@Rustin170506)
  * [ ] Approve RFC ([cargo](https://github.com/rust-lang/cargo), [crates-io](https://github.com/rust-lang/crates.io) ![Team][])
  * [ ] Implementation in Cargo side (@Rustin170506)
  * [ ] Inside Rust blog post inviting feedback (@Rustin170506)
  * [ ] Stabilization decision ([cargo](https://github.com/rust-lang/cargo) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.

**Comment by hi-rustin** [comment]
Update(2024-07-30):
Created an issue on the crates.io side, and let's start discussing how to implement it on the crates.io side first.

**Comment by Rustin170506** [comment]
Update(2024-08-15):
I have written a detailed API design, feel free to discuss it at https://github.com/rust-lang/crates.io/issues/9193#issuecomment-2291379632

**Comment by Rustin170506** [comment]
Updated(2024-09-13):
I have created the initial PR for it. See: https://github.com/rust-lang/crates.io/pull/9423

**Comment by Rustin170506** [comment]
Updated(2024-10-25):
The PR https://github.com/rust-lang/crates.io/pull/9423 has been merged. I am working on the frontend feature.
