### ISSUE TITLE
Assemble project goal slate

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#102]
| Metadata      | |
| --------      | --- |
| Owner(s)      | @nikomatsakis |
| Team(s)       | [leadership-council](https://github.com/rust-lang/leadership-council) |
| Goal document | [2024h2/Project-goal-slate](https://rust-lang.github.io/rust-project-goals/2024h2/Project-goal-slate.html) |

## Summary

Run an experimental goal program during the second half of 2024

## Tasks and status

* [x] RFC decision ([leadership-council](https://github.com/rust-lang/leadership-council) ![Team][])
* [x] Inside Rust blog post inviting feedback
* [x] Top-level Rust blog post announcing result (https://blog.rust-lang.org/2024/08/12/Project-goals.html)
* [x] September update (https://blog.rust-lang.org/2024/09/23/Project-Goals-Sep-Update.html)
* [x] October update
* [x] Kick off 2025h2 planning
* [ ] November update
* [ ] December update

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.

**Comment by nikomatsakis** [comment]
Update: RFC https://github.com/rust-lang/rfcs/pull/3672 was merged today, along with preliminary support for triagebot integration. Next steps are:

* update the rust-lang/rust-project-goals site with more instructions and to clarify state of things
* author Inside Rust blog post and all@ email to bring people up to date
* author public blog post with roadmap announcement
* finalize schedule for how we'll be doing updates from now on

My current thought is that I'll post a roadmap update on a 6 week cadence, roughly aligned with Rust releases.

(Also, in theory, this comment, along with others posted to tracking issues on this repo, will be echoed to Zulip! Let's see if it happens.)

**Comment by nikomatsakis** [comment]
**Key developments:**

* Authored a [public announcement](https://blog.rust-lang.org/2024/08/12/Project-goals.html) post about the goals which went live on Aug 12, and then I took a long vacation. I'm back now. 
* Plan to revamp the https://rust-lang.github.io/rust-project-goals/ website to link to tracking goals and generally make the status clearer.
* Began work towards the first update blog post, drafting to begin Sep 16.

**Comment by nikomatsakis** [comment]
Key developments:

* Posted the September update.
* Created more automated infrastructure to prepare the October update. The `cargo run -- updates 2024h2` command now makes use of an LLM to summarize the updates that people post into one or two sentences so that we can have a concise table. The goal is to make publishing regular updates as "turnkey" as possible so that we are able to focus our energy on getting the goals *done*.
* I am planning to kick off the 2025H1 goal proposal season by the start of November 🤞 -- more likely by the second week.

**Comment by nikomatsakis** [comment]
October update is live:

https://blog.rust-lang.org/2024/10/31/project-goals-oct-update.html

Next steps:

* Prepare the blog post soliciting proposals for the next round of goals, including a "mini-retrospective"
* Update the website in preparation for that

**Comment by nikomatsakis** [comment]
Kicked off 2025h1 planning:

https://blog.rust-lang.org/inside-rust/2024/11/04/project-goals-2025h1-call-for-proposals.html
