### ISSUE TITLE
Associated type position impl trait

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#103]
| Metadata      | |
| --------      | --- |
| Owner(s)      | @oli-obk |
| Team(s)       | [lang](http://github.com/rust-lang/lang-team), [types](https://github.com/rust-lang/types-team) |
| Goal document | [2024h2/ATPIT](https://rust-lang.github.io/rust-project-goals/2024h2/ATPIT.html) |

## Summary

Stable support for `impl Trait` in the values of associated types (aka "associated type position impl trait" or ATPIT)

## Tasks and status

* [ ] Implementation (@oli-obk)
* [ ] FCP decisions ([types](https://github.com/rust-lang/types-team) ![Team][])
* [ ] Stabilization decision ([types](https://github.com/rust-lang/types-team), [lang](http://github.com/rust-lang/lang-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by oli-obk** [comment]
The remaining blockers for this feature are

* make a lang decision on whether methods with the ATPIT in their signature need to actually define the ATPIT (https://github.com/rust-lang/rust/pull/123046)
* Switch remaining `DefineOpaqueTypes::No` to `Yes`
    * horrible unreviewable PR: https://github.com/rust-lang/rust/pull/127034 instead try one of the following
        * try revealing opaque type in candidate assembly and bail as ambiguous while no concrete hidden type available https://github.com/oli-obk/rust/tree/infer instead (see https://rust-lang.zulipchat.com/#narrow/stream/144729-t-types/topic/opaque.20types.20and.20ATPIT.20oh.20my/near/451059084 for details)
        * or try normalizing opaques to infer vars eagerly https://github.com/rust-lang/rust/compare/master...oli-obk:infer2?expand=1 (may need `AliasRelate` predicate support in the old solver? not sure) Read https://hackmd.io/lXnLt7nsSS2NUFGHKW4B3Q to see what we can do to make old solver's opaques more similar to the new solver
    * unreviewed PR: https://github.com/rust-lang/rust/pull/126316
    * unopened PR: https://github.com/oli-obk/rust/pull/new/define_opaque_types22


Not necessary for stabilization, but would be cool if `#[defines()]` would make a method not define the opaque type, even if it is in the signature (see https://github.com/rust-lang/rust/pull/128440 for an impl of the `#[defines]` attribute)

**Comment by oli-obk** [comment]
No progress (that I know of) since last update

**Comment by oli-obk** [comment]
No progress

**Comment by nikomatsakis** [comment]
I'm going to close this goal -- consensus is that we will not reach stabilization in this goal period. We'll try again next time!
