### ISSUE TITLE
Prepare const traits for stabilization

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#106]
| Metadata         | |
| --------         | --- |
| Point of contact | @oli-obk |
| Team(s)          | [compiler](http://github.com/rust-lang/compiler-team), [lang](http://github.com/rust-lang/lang-team), [types](https://github.com/rust-lang/types-team) |
| Goal document    | [2025h1/const-trait](https://rust-lang.github.io/rust-project-goals/2025h1/const-trait.html) |

## Summary

Prepare `const Trait` bounds for stabilization.

## Tasks and status

* [x] Lang-team experiment ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [x] Experimental implementation (@fee1-dead, @compiler-errors)
* [x] Author RFC (@oli-obk)
* [x] Adjust implementation to match RFC ()
* [ ] Call for testing (@oli-obk)
* [ ] Standard reviews ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
* [x] Design meeting ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [x] Lang-team champion ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] RFC decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] RFC secondary review ([types](https://github.com/rust-lang/types-team) ![Team][])
* [ ] Author specification 1st draft (@oli-obk)
### Formalize const-traits in a-mir-formality
* [ ] Discussion and moral support ([types](https://github.com/rust-lang/types-team) ![Team][])
* [ ] Implementation (@tiif)
* [ ] Mentoring and kibbitzing (@nikomatsakis, @oli-obk)

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.

**Comment by fee1-dead** [comment]
Update 2024-07-27:
* **Key developments:** We recently landed my [new proposed desugaring](https://hackmd.io/@beef/HJyX7wF70) in #120639, which is a big step towards having a robust model of const traits in the type system.

**Comment by fee1-dead** [comment]
Update 2024-08-25:

* **Key developments:** A handful of cleanups ([#126552](https://github.com/rust-lang/rust/pull/126552) [#126737](https://github.com/rust-lang/rust/pull/126737) [#127452](https://github.com/rust-lang/rust/pull/127452) [#128424](https://github.com/rust-lang/rust/pull/128424) [#129500](https://github.com/rust-lang/rust/pull/129500)), opened a project group repo for [tracking](https://github.com/rust-lang/project-const-traits/issues) design considerations. A proposed solution to making implied bounds with super traits work ([project-const-traits#2](https://github.com/rust-lang/project-const-traits/issues/2)) is open: [#129499](https://github.com/rust-lang/rust/pull/129499)

**Comment by fee1-dead** [comment]
Update 2024-10-02:

* **Key developments:** With the PR for supporting implied super trait bounds landed ([#129499](https://github.com/rust-lang/rust/pull/129499)), the current implementation is mostly complete in that it allows most code that should compile, and should reject all code that shouldn't. Further testing is required, with our next steps being improving diagnostics ([#131152](https://github.com/rust-lang/rust/pull/131152)), and fixing more holes before we'd be comfortable with adding const traits back to core.

**Comment by fee1-dead** [comment]
Update 2024-11-20:

[#131985](https://github.com/rust-lang/rust/pull/131985) by @compiler-errors completely restructured the way const traits are desugared, which made the design easier to understand and more robust against our current unit tests. Since then, there had been significant development and cleanup for the feature, with [#131968](https://github.com/rust-lang/rust/pull/131968) [#132118](https://github.com/rust-lang/rust/pull/132118) [#132168](https://github.com/rust-lang/rust/pull/132168) [#132169](https://github.com/rust-lang/rust/pull/132169) [#132227](https://github.com/rust-lang/rust/pull/132227) [#132275](https://github.com/rust-lang/rust/pull/132275) [#132344](https://github.com/rust-lang/rust/pull/132344) [#132366](https://github.com/rust-lang/rust/pull/132366) [#132368](https://github.com/rust-lang/rust/pull/132368) [#132479](https://github.com/rust-lang/rust/pull/132479) [#132823](https://github.com/rust-lang/rust/pull/132823) among the ones that got merged, and [#133216](https://github.com/rust-lang/rust/pull/133216) [#133218](https://github.com/rust-lang/rust/pull/133218) that are still open.

With the recent work, we are very close to being able to dogfooding the feature on the standard library again, and the current implementation is the closest we have towards something that can be stabilized.

**Comment by fee1-dead** [comment]
Update 2024-12-30: (sorry for the delay!)

We began adding a small set of const traits and implementation in the compiler, while carefully looking for improvements in our implementation. We constified `Add` in https://github.com/rust-lang/rust/pull/133237 and `Deref`/`DerefMut` in https://github.com/rust-lang/rust/pull/133260.

A lot of the credits for implementing this feature goes to @compiler-errors, who authored these PRs (let me know if I have missed some): https://github.com/rust-lang/rust/pull/133926 https://github.com/rust-lang/rust/pull/134637 https://github.com/rust-lang/rust/pull/134638 

There was more progress on implementing stability for the const traits feature: https://github.com/rust-lang/rust/pull/132823 (didn't include in the previous update, sorry), and https://github.com/rust-lang/rust/pull/133999.

A couple of PRs constifying more traits are also open: https://github.com/rust-lang/rust/pull/133995 https://github.com/rust-lang/rust/pull/134628

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h1

**Comment by oli-obk** [comment]
I opened an RFC (https://github.com/rust-lang/rfcs/pull/3762) and we had a lang team meeting about it. Some design exploration and bikeshedding later we have settled on using (const)instead of ~const along with some more annotations for explicitness and some fewer annotations in other places. The RFC has been updated accordingly. There is still ongoing discussions about reintroducing the "fewer annotations" for redundancy and easier processing by humans.

**Comment by oli-obk** [comment]
No updates

**Comment by oli-obk** [comment]
No updates on my side, but we may be going back to the original proposal (modulo syntax) with a syntax that is extensible to more opt-out marker effects without lots of repetition of the `const` keyword

**Comment by oli-obk** [comment]
The following contributors have made many libcore traits `const`:

* @Daniel-Aaron-Bloom
* @estebank 
* @Randl
* @SciMind2460

@fee1-dead has also updated the syntax to allow for `const trait Trait {}` declarations instead of `#[const_trait] trait Trait {}`.

Thanks y'all for moving this feature along!

We have encountered few issues, but there is one major one:

without `dyn [const] Trait` support we cannot turn any of the `core::fmt` traits const in a usable way. This in turn makes things like `Result::unwrap` not usable in const contexts without using `const_eval_select` to not actually perform any formatting within const contexts.

It is my belief that now would be a good time to call for testing to get community input on the current syntax and behaviour.

**Comment by tomassedovic** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2026

**Comment by fee1-dead** [comment]
We discussed some potential next steps during the all hands and are trying to implement some new ways to eliminate the need for `Destruct`. On the language side, TC is preparing a document that should hopefully drive us to consensus to stabilize in the near future, hopefully this year.

**Comment by fee1-dead** [comment]
- Me and oli are reviewing a draft proposal by TC which should help pave our path forward
- From discussions among team members, a minimally stabilizable subset that avoids questions on syntax was floated. I will write that up in the upcoming weeks to see if this is feasible, which should help fast track it to stabilization

**Comment by fee1-dead** [comment]
* I've started working on a `min_const_trait_impl` feature both at the compiler side and at the language design proposal side.
