### ISSUE TITLE
Patterns of empty types

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#115]
| Metadata      | |
| --------      | --- |
| Owner(s)      | @Nadrieril |
| Team(s)       | [compiler](http://github.com/rust-lang/compiler-team), [lang](http://github.com/rust-lang/lang-team) |
| Goal document | [2024h2/Patterns-of-empty-types](https://rust-lang.github.io/rust-project-goals/2024h2/Patterns-of-empty-types.html) |

## Summary

Introduce an RFC for never patterns or other solutions for patterns involving uninhabited types.

## Tasks and status

* [x] Stabilize `min_exhaustive_patterns` (@Nadrieril)
* [x] Defer linting of newly-unreachable arms til later (@Nadrieril)
* [x] Write up "never patterns" RFC (@Nadrieril)
* [ ] Submit RFC, discuss and wait for acceptance ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] Implement never patterns (@Nadrieril)
* [ ] Amend `exhaustive_patterns` to only apply to the case of empty types behind references (@Nadrieril)
* [ ] Decide on stabilization of `exhaustive_patterns` ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] Decide on linting of the newly-unreachable arms ([lang](http://github.com/rust-lang/lang-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.

**Comment by Nadrieril** [comment]
Here's the status we're at today:
- The [`exhaustive_patterns`](https://github.com/rust-lang/rust/issues/51085) feature has been usable for years but was deemed not-stabilizable-as-is; I aim to deprecate it as part of this goal;
- The [`min_exhaustive_patterns`](https://github.com/rust-lang/rust/issues/119612) feature has been proposed, implemented, and [approved for stabilization](https://github.com/rust-lang/rust/pull/122792#issuecomment-2106338444). Stabilization was blocked on improving lints; this is about to be resolved;
- My [proposal for never patterns](https://github.com/rust-lang/rust/issues/118155) got sufficient approval to enable experimentation. The unstable feature is now in a usable state, though not yet complete;
- I have an [RFC draft for never patterns](https://hackmd.io/XPZfEzcGRy2P7woORHUOcQ) lying around. It needs to be fleshed out and updated in light of `min_exhaustive_patterns` being stabilized, after which we can start the RFC process.

**Comment by Nadrieril** [comment]
Update since last time:
- The  [`min_exhaustive_patterns`](https://github.com/rust-lang/rust/issues/119612) feature has been stabilized, it will be accessible in 1.82.0;
- The stabilization caused issues because we went from requiring some match arms to warning against them. [There was some discussion on the topic](https://github.com/rust-lang/rust/issues/129031), and it was decided to revert the linting behavior for now and find a solution that has a smoother transition.

Next steps:
- Backport the approved linting change to beta;
- Implement whatever linting mitigation we end up deciding on;
- Finish writing up the never patterns RFC.

**Comment by Nadrieril** [comment]
Update since last time:
- We reverted the linting behavior until an unspecified date

Next steps:
- Decide what we want to do with linting;
- Write the never patterns RFC.

**Comment by Nadrieril** [comment]
Update since last time:

- The [never patterns RFC](https://github.com/rust-lang/rfcs/pull/3719) was posted.
- Feedback on the RFC suggests that the question of "which arms can be omitted" isn't as orthogonal as I hoped, so I'll switch focus to that.

Next steps:
- Amend `exhaustive_patterns` to only apply to the case of empty types behind references;
- Propose stabilization of `exhaustive_patterns`, i.e. allow omitting a match arm even when the empty type is behind a reference.

**Comment by Nadrieril** [comment]
No progress since last time.

**Comment by Nadrieril** [comment]
Summary of the progress over the semester: I went at my own pace which is a slow pace. I wrote and posted the never patterns RFC as an attempt to make progress without figuring out the whole picture, and the general feedback was "we want to see the whole picture". Next step will be to write up an RFC that includes a clear proposal for which empty patterns can and cannot be omitted. This is 100% bottlenecked on my own writing bandwidth (reach out if you want to do this together!).

I did not end up making much use of the project goal structure, so I decided not to renew this goal for 2025H1. I will keep working on it at my own pace. Stay tuned for future developments!
