### ISSUE TITLE
Stabilize cargo-script

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#119]
| Metadata         | |
| --------         | --- |
| Point of contact | @epage |
| Team(s)          | [cargo](https://github.com/rust-lang/cargo), [compiler](http://github.com/rust-lang/compiler-team), [lang](http://github.com/rust-lang/lang-team), [rustdoc](https://github.com/rust-lang/rust) |
| Goal document    | [2026/cargo-script](https://rust-lang.github.io/rust-project-goals/2026/cargo-script.html) |

## Summary

Stabilize support for "cargo script", the ability to have a single file that contains both Rust code and a `Cargo.toml`.

## Tasks and status

[Team]: https://img.shields.io/badge/Team%20ask-red

---
Note: we have updated the body to match the 2026 goal. Your original text is preserved below. <details>

| Metadata         | |
| --------         | --- |
| Point of contact | @epage |
| Team(s)          | [cargo](https://github.com/rust-lang/cargo), [compiler](http://github.com/rust-lang/compiler-team), [lang](http://github.com/rust-lang/lang-team), [lang-docs](https://www.rust-lang.org/governance/teams) |
| Goal document    | [2025h2/cargo-script](https://rust-lang.github.io/rust-project-goals/2025h2/cargo-script.html) |

## Summary

Stabilize support for "cargo script", the ability to have a single file that contains both Rust code and a `Cargo.toml`.

## Tasks and status

* [ ] Discussion and moral support ([cargo](https://github.com/rust-lang/cargo), [compiler](http://github.com/rust-lang/compiler-team) ![Team][])
* [ ] Ensure Cargo implementation (@epage)
### Implement language feature `frontmatter`
* [ ] Rust-analyzer implementation (@epage)
* [ ] rustfmt implementation (@epage)
* [ ] Standard reviews ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
* [ ] Author call for testing blog post (@epage)
### Stabilize language feature `frontmatter`
* [ ] Author Reference PR (@epage)
* [ ] Review/revise Reference PR ([lang-docs](https://www.rust-lang.org/governance/teams) ![Team][])
* [ ] Author stabilization report (@epage)
* [ ] Author stabilization PR (@epage)
* [ ] Stabilization decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

---
Note: we have updated the body to match the 2025h2 goal. Your original text is preserved below. <details>
| Metadata      | |
| --------      | --- |
| Owner(s)      | @epage |
| Team(s)       | [cargo](https://github.com/rust-lang/cargo), [lang](http://github.com/rust-lang/lang-team) |
| Goal document | [2024h2/cargo-script](https://rust-lang.github.io/rust-project-goals/2024h2/cargo-script.html) |
| See also | https://github.com/rust-lang/cargo/issues/12207 |

## Summary

Stablize support for "cargo script", the ability to have a single file that contains both Rust code and a `Cargo.toml`.

## Tasks and status

See rust-lang/cargo#12207

[Team]: https://img.shields.io/badge/Team%20ask-red

</details>
</details>

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.

**Comment by epage** [comment]
Key developments: What has happened since the last time. It's perfectly ok to list "nothing" if that's the truth, we know people get busy.
- None

Blockers: List any Rust teams you are waiting on and what you are waiting for.
- Time.  Expectation is to get to this in a couple months
 
Help wanted: Are there places where you are looking for contribution or feedback from the broader community?
- rustc parser for code fence syntax
- see also rust-lang/cargo#12207

**Comment by epage** [comment]
No change since the last update.

**Comment by epage** [comment]
Key developments: What has happened since the last time. It's perfectly ok to list "nothing" if that's the truth, we know people get busy.
- rust-lang/cargo#14404
- rust-lang/cargo#14591

Blockers: List any Rust teams you are waiting on and what you are waiting for.
- Time. Expectation is to get to this in a couple weeks

Help wanted: Are there places where you are looking for contribution or feedback from the broader community?
- rustc parser for code fence syntax
- see also rust-lang/cargo#12207

**Comment by epage** [comment]
Key developments: What has happened since the last time. It's perfectly ok to list "nothing" if that's the truth, we know people get busy.

- https://github.com/rust-lang/cargo/pull/14925 posted and merged


Blockers: List any Rust teams you are waiting on and what you are waiting for.

- None

Help wanted: Are there places where you are looking for contribution or feedback from the broader community?

- Writing frontmatter support in rustc.  rustfmt folks are asking for it to be represented in the AST.

**Comment by lqd** [comment]
This project goal was actually carried over from 2024h2, in https://github.com/rust-lang/rust-project-goals/pull/294

**Comment by epage** [comment]
Key developments: What has happened since the last time. It's perfectly ok to list "nothing" if that's the truth, we know people get busy.
- @fee1-dead posted rust-lang/rust#140035 for compiler support for frontmatters (which supersedes rust-lang/rust#137193)

Blockers: List any Rust teams you are waiting on and what you are waiting for.

Help wanted: Are there places where you are looking for contribution or feedback from the broader community?

**Comment by epage** [comment]
Key developments:
- rust-lang/rust#140035 has been merged

Blockers:

Help wanted:

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by tomassedovic** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2026
