### ISSUE TITLE
Promoting Parallel Front End

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#121]
| Metadata         | |
| --------         | --- |
| Point of contact | @SparrowLii |
| Team(s)          | [compiler](http://github.com/rust-lang/compiler-team), [wg-parallel-rustc](https://forge.rust-lang.org/compiler/working-areas.html) |
| Goal document    | [2026/parallel-front-end](https://rust-lang.github.io/rust-project-goals/2026/parallel-front-end.html) |

## Summary

Continue with stabilization and performance improvements to the parallel front-end, continuing from the [2025h2 goal](https://rust-lang.github.io/rust-project-goals/2025h2/parallel-front-end.html).

## Tasks and status

[Team]: https://img.shields.io/badge/Team%20ask-red

---
Note: we have updated the body to match the 2026 goal. Your original text is preserved below. <details>

| Metadata         | |
| --------         | --- |
| Point of contact | @SparrowLii |
| Team(s)          | [compiler](http://github.com/rust-lang/compiler-team) |
| Goal document    | [2025h2/parallel-front-end](https://rust-lang.github.io/rust-project-goals/2025h2/parallel-front-end.html) |

## Summary

Continue with stabilization and performance improvements to parallel front-end, continuing from the [2025h1 goal](https://rust-lang.github.io/rust-project-goals/2025h1/parallel-front-end.html).

## Tasks and status

* [ ] Implementation (@SparrowLii)
* [ ] Author tests (@SparrowLii)
* [ ] Discussion and moral support ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

---
Note: we have updated the body to match the 2025h2 goal. Your original text is preserved below. <details>

| Metadata         | |
| --------         | --- |
| Point of contact | @SparrowLii |
| Team(s)          | [compiler](http://github.com/rust-lang/compiler-team) |
| Goal document    | [2025h1/parallel-front-end](https://rust-lang.github.io/rust-project-goals/2025h1/parallel-front-end.html) |

## Summary

Continue to parallelize front-end stabilization and performance improvements, continuing from the [2024h2 goal](https://rust-lang.github.io/rust-project-goals/2024h2/parallel-front-end.html).

## Tasks and status

* [ ] Implementation (@SparrowLii)
* [ ] Author tests (@SparrowLii)
* [ ] Discussion and moral support ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

</details>
</details>

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.

**Comment by SparrowLii** [comment]
* **Key developments:** *
Use ui test to locate and solve the ICE problem of parallelfront end
Discussed strategies for customizing and enhancing the compiler testing suit to address hard-to-reproduce bugs
* **Blockers:** 
Many deadlock issues are difficult to reproduce and resolve
* **Help wanted:**
Help test the deadlock code in the [issue list](https://github.com/rust-lang/rust/labels/WG-compiler-parallel) and try to reproduce the issue

**Comment by SparrowLii** [comment]
* **Key developments:** *
Add the cases in the [issue list](https://github.com/rust-lang/rust/labels/WG-compiler-parallel) to the UI test to reproduce the bug or verify the non-reproducibility
* **Blockers:** 
null
* **Help wanted:**
Help test the deadlock code in the [issue list](https://github.com/rust-lang/rust/labels/WG-compiler-parallel) and try to reproduce the issue

**Comment by SparrowLii** [comment]
* **Key developments:** *
Still in the process of determining the cause of the deadlock through local testing and compiler code analysis.
* **Blockers:** 
null
* **Help wanted:**
Help test the deadlock code in the [issue list](https://github.com/rust-lang/rust/labels/WG-compiler-parallel) and try to reproduce the issue

**Comment by nikomatsakis** [comment]
@SparrowLii opened a “proposed 2025H1 project goal](https://rust-lang.github.io/rust-project-goals/2025h1/parallel-front-end.html) to continue this work. The plans for the next 6 months are

- Solve reproducible deadlock issues via [tests](https://github.com/rust-lang/rust/pull/132051).
- Enable parallel frontends in bootstrap.
- Continue to improve parallel compilation performance, with the average speed increase from 20% to 25% under 8 cores and 8 threads.
- Communicate with Cargo team on the solution and plan to support parallel front end.

**Comment by SparrowLii** [comment]
* **Key developments:** *
We discussed solutions to avoid potential deadlocks in mechanism, and so far disabling work-stealing in rayon's subloops is an effective solution. We will try to incorporate related modification PR: https://github.com/rust-lang/rustc-rayon/pull/12
* **Blockers:** 
null
* **Help wanted:**
Help test the deadlock code in the [issue list](https://github.com/rust-lang/rust/labels/WG-compiler-parallel) and try to reproduce the issue

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h1

**Comment by SparrowLii** [comment]
* **Key developments:** *
Several deadlock issue that remain for more than a year were resolved by #137731
The new test suit for parallel front end is being improved
* **Blockers:** 
null
* **Help wanted:**
Help test the deadlock code in the [issue list](https://github.com/rust-lang/rust/labels/WG-compiler-parallel) and try to reproduce the issue

**Comment by SparrowLii** [comment]
* **Key developments:** The main bottleneck is the customization of the dependent `rustc-rayon` library. @oli-obk and @Zoxc are helping to move this forward.
* **Blockers:** null
* **Help wanted:** Help test the deadlock code in the [issue list](https://github.com/rust-lang/rust/labels/WG-compiler-parallel) and try to reproduce the issue

**Comment by SparrowLii** [comment]
* **Key developments:** We bring rustc-rayon in rustc's working tree, the [PR](https://github.com/rust-lang/rust/pull/143035) that fixes several deadlock issues has been merged. 
* **Blockers:** null
* **Help wanted:** Help test the deadlock code in the [issue list](https://github.com/rust-lang/rust/issues?q=is%3Aopen%20label%3AA-parallel-compiler) and try to reproduce the issue

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h2

**Comment by tomassedovic** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2026

**Comment by petrochenkov** [comment]
* **Key developments:**
  - https://github.com/rust-lang/rust/pull/151509 Fixed the last remaining class of commonly occurring crashes
  - https://github.com/rust-lang/rust/pull/143035 Fixed the last known deadlock issues
  - https://github.com/rust-lang/rust/pull/153801 UI test suite now supports running in parallel mode.
  - https://github.com/rust-lang/rust/pull/158307 Enabling the parallel UI test suite on CI is in progress
  - https://github.com/rust-lang/rust/pull/154354 A lot of tests for fixed parallel frontend issues were added
  - https://github.com/rust-lang/rust/issues/154314 Most of diagnostic reproducibility issues in the parallel UI test suite were fixed or worked around with normalization
  - https://github.com/rust-lang/rust/issues?q=state%3Aclosed%20label%3AA-parallel-compiler%20sort%3Aupdated-desc Open `A-parallel-compiler` were triaged and many of them closed because they no longer reproduce (when there's a reproducer in the parallel UI test suite), or because they are old, have no reproducer and other similar issues were closed
  - https://github.com/rust-lang/rustc-perf/pull/2421 Adding a benchmark suite for the parallel frontend to rustc-perf is in progress.
  - https://github.com/rust-lang/compiler-team/issues/1005 MCP with a stabilization plan for rustc parallel frontend was submitted
* **Blockers:**
  - None at the moment
* **Help wanted:**
  - Check whether https://github.com/rust-lang/rust/issues/152662 still reproduces (make sure it reproduces on a33907a7a5381473eec8bcfa0c56e05a856a911c in your setup).

**Comment by petrochenkov** [comment]
* **Key developments:**
  - The last large group of disabled tests in the parallel test suite was enabled (https://github.com/rust-lang/rust/pull/156716), there's also a group of tests with query cycles, but there's no possible fix in sight for them.
  - The parallel test suite was enabled on CI first in non-blocking mode (https://github.com/rust-lang/rust/pull/158307), and then later switched to blocking (https://github.com/rust-lang/rust/pull/159833).
  - The first half of support for parallel benchmarks on rustc-perf (backend) was merged (https://github.com/rust-lang/rustc-perf/pull/2491).
  - The second half of support for parallel benchmarks on rustc-perf (site frontend) is in progress.
  - Support for `--jobs(,-frontend,-backend,-linker)` options limiting rustc parallelism was implemented, review feedback was addressed, the PR (https://github.com/rust-lang/rust/pull/159675) is currently waiting on review.
  - Issue https://github.com/rust-lang/rust/pull/152662 was verified to not reproduce on nightly.
  - Some documentation (https://github.com/rust-lang/rust/pull/159408) and cleanup (https://github.com/rust-lang/rust/pull/159390) PRs for jobserver support in rustc were merged.
* **Blockers:**
  - None at the moment
* **Help wanted:**
  - None at the moment

**Comment by petrochenkov** [comment]
* **Key developments:**
  - Support for `-j` options limiting rustc parallelism was merged after some updates (https://github.com/rust-lang/rust/pull/159675).
  - Further tweaks to `--jobs` options were implemented, including the `--reproducible` option (https://github.com/rust-lang/rust/pull/160448, https://github.com/rust-lang/rust/pull/160424, https://github.com/rust-lang/rust/pull/160697), two of those PRs are still waiting on review.
  - One fix for backend parallelism limiting was submitted (https://github.com/rust-lang/rust/pull/160387).
  - Non-optional CI testing for the parallel frontend was merged (https://github.com/rust-lang/rust/pull/159833).
  - Some more parallel testing fixes were merged (https://github.com/rust-lang/rust/pull/160147, https://github.com/rust-lang/rust/pull/160013).
  - rustc-perf: initial version of the parallel benchmark support in the site frontend was submitted (https://github.com/rust-lang/rustc-perf/pull/2529).
  - The remaining open issues are being debugged, with focus on correctness/ICEs and binary reproducibility.
    - https://github.com/rust-lang/rust/pull/154056 "[ICE]: cycle detected when computing function signature" was verified to be fixed and was closed.
    - https://github.com/rust-lang/rust/pull/140413 was verified to be fixed, a test was submitted in https://github.com/rust-lang/rust/pull/161353.
    - Overflow checks were enabled in `rustc_thread_pool` (https://github.com/rust-lang/rust/pull/161296), they were previously disabled a few years ago due to overflow issues.
    - https://github.com/rust-lang/rust/pull/129094 was debugged, a fix was submitted in https://github.com/rust-lang/rust/pull/161450.
* **Blockers:**
  - Reviews for https://github.com/rust-lang/rust/pull/160697, https://github.com/rust-lang/rust/pull/160448, https://github.com/rust-lang/rust/pull/160197 and https://github.com/rust-lang/rust/pull/161450.
* **Help wanted:**
  - Finishing the started work on supporting parallel benchmarks in rustc-perf site frontend (https://github.com/rust-lang/rustc-perf/pull/2529).
 * **Next steps:**
   - Submit a PR enabling the parallel frontend on nightly (blocked on https://github.com/rust-lang/rust/pull/160697 and https://github.com/rust-lang/rust/pull/160448).
   - Proactively find binary reproducibility issues in top N crates.
   - Collect and compare compilation times from the standard rustc-perf benchmarks in several scenarios (1 vs 2 vs 4 vs 8 vs 16 threads).
