### ISSUE TITLE
Use annotate-snippets for rustc diagnostic output

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#123]
| Metadata      | |
| --------      | --- |
| Owner(s)      | @estebank, @Muscraft |
| Team(s)       | [compiler](http://github.com/rust-lang/compiler-team) |
| Goal document | [2024h2/annotate-snippets](https://rust-lang.github.io/rust-project-goals/2024h2/annotate-snippets.html) |

## Summary

Switch to annotate-snippets for rendering rustc's output, with no loss of functionality or visual regressions.

## Tasks and status

* [ ] Reach output parity of rustc/annotate-snippets
  * [ ] Port a subset of rustc's UI tests (@Muscraft)
  * [ ] Make list of current unnaddressed divergences (@Muscraft)
  * [ ] address divergences (@Muscraft)
* [ ] Initial use of annotate-snippets
  * [ ] update annotate-snippets to latest version
  * [ ] teach cargo to pass annotate-snippets flag (@estebank)
  * [ ] add ui test mode comparing new output
  * [ ] switch default nightly rustc output
* [ ] Production use of annotate-snippets
  * [ ] switch default rustc output
  * [ ] release notes
  * [ ] switch ui tests to only check new output
  * [ ] dedicated reviewer ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
* [ ] Standard reviews ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by Muscraft** [comment]
The last few weeks I have been trying to get suggestions working within `annotate-snippets`, and have been able to match `rustc` suggestion output in most cases. Most of my time was spent trying to understand the different rendering styles for suggestions, and how they should be adapted to fit within `annotate-snippets`.

![Image](https://github.com/user-attachments/assets/42e0fc2f-ed81-4f09-80c6-6dd8837cef98)
![Image](https://github.com/user-attachments/assets/4e3d3354-90ec-4217-90ab-11ec096823a9)

**Comment by Muscraft** [comment]
I have been a bit busy over the past two months, so I haven't had as much time to work on `annotate-snippets` as I had hoped. That said, progress was still being made!

I continued working on suggestions, but as I got deeper into the implementation, I realized getting the corner cases correct would be very difficult with the `annotate-snippets` architecture. I started work on a more direct translation from `rustc`, and quickly ended up with something that closely matched it at the cost of significant differences from how annotations are rendered. These differences, and some problems I noticed with the API for suggestions, led to a discussion with @epage about how to resolve these problems. During the discussion, I realized it would be beneficial if the internals of `annotate-snippets` resembled `rustc` as it would make it easier for contributors to `rustc` to contribute to `annotate-snippets`. @epage was helpful enough to design a new API, which resolved my suggestion API concerns and should make it easier for `annotate-snippets`'s internals to resemble `rustc`. Initial work on the new design has yielded positive results, so I am hopeful this was a good decision. During all of this, I started to work on a tool that should help convert some of `rustc`'s UI tests to be used in `annotate-snippet`'s testsuite.

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h1

**Comment by Muscraft** [comment]
While my time was limited these past few months, lots of progress was made! I was able to align `annotate-snippets` internals with `rustc`'s [`HumanEmitter`](https://github.com/rust-lang/rust/blob/5cc60728e7ee10eb2ae5f61f7d412d9805b22f0c/compiler/rustc_errors/src/emitter.rs#L629) and get the new API implemented. These changes have not been merged yet, but [they can be found here](https://github.com/Muscraft/annotate-snippets-rs/tree/feedback). As part of this work, I got `rustc` using `annotate-snippets` as its only renderer. During all of this, I started working on making `rustc` use `annotate-snippets` as its only renderer, which turned out to be a huge benefit. I was able to get a feel for the new API while addressing rendering divergences. As of the time of writing, all but ~30 tests of the roughly 18,000 UI tests are passing.

```
test result: FAILED. 18432 passed; 29 failed; 193 ignored; 0 measured; 0 filtered out; finished in 102.32s
```

Most of the failing tests are caused by a few things:
- `annotate-snippets` right aligns numbers, whereas `rustc` left aligns
- `annotate-snippets` doesn't handle multiple suggestions for the same span very well
- Problems with handling `FailureNote`
- `annotate-snippets` doesn't currently support colored labels and titles, i.e., the magenta highlight `rustc` uses
- `rustc` wants to pass titles similar to `error: internal compiler error[E0080]`, but `annotate-snippets` doesn't support that well
- differences in how `rustc` and `annotate-snippets` handle term width during tests
  - When testing, `rustc` uses `DEFAULT_COLUMN_WIDTH` and does not subtract the code offset, while `annotate-snippets` does
- Slight differences in how "newline"/end of line highlighting is handled
- JSON output rendering contains color escapes

**Comment by Muscraft** [comment]
Key developments
- The new API for `annotate-snippets` got merged (and tweaked)
- [`annotate-snippets` passed all of `rustc`'s UI tests for the first time](https://asciinema.org/a/MlUN66AxlyLbaJ9VP8zDWlutt)
- I started getting `annotate-snippets` ready for release
- [I started opening PRs](https://github.com/rust-lang/rust/pulls?q=is%3Apr+author%3AMuscraft+created%3A%3E2025-03-31+) to get `rustc` to match `annotate-snippets` planned output changes

Blockers

Help wanted
