### ISSUE TITLE
User-wide build cache

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#124]
| Metadata      | |
| --------      | --- |
| Owner(s)      |  |
| Team(s)       | [cargo](https://github.com/rust-lang/cargo) |
| Goal document | [2024h2/user-wide-cache](https://rust-lang.github.io/rust-project-goals/2024h2/user-wide-cache.html) |

## Summary

Extend Cargo's caching of intermediate artifacts across a workspace to caching them across all workspaces of the user.

## Tasks and status

* [ ] User-wide caching
  * [ ] Implementation ()
  * [ ] Standard reviews ([cargo](https://github.com/rust-lang/cargo) ![Team][])
  * [ ] Mentoring and guidance (@epage)
  * [ ] Design meeting ([cargo](https://github.com/rust-lang/cargo) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.
