### ISSUE TITLE
Instrument the Rust standard library with safety contracts

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#126]
| Metadata         | |
| --------         | --- |
| Point of contact | @celinval |
| Team(s)          | [compiler](http://github.com/rust-lang/compiler-team), [libs](https://github.com/rust-lang/libs-team) |
| Goal document    | [2025h1/std-contracts](https://rust-lang.github.io/rust-project-goals/2025h1/std-contracts.html) |

## Summary

Finish the implementation of the contract attributes proposed in the compiler [MCP-759],
and port safety contracts from the [verify-rust-std] fork to the Rust standard library.

## Tasks and status

* [ ] Discussion and moral support ([libs](https://github.com/rust-lang/libs-team) ![Team][])
### Experimental Contract attributes
* [x] Author MCP
* [ ] Implementation (@celinval)
* [ ] Standard reviews ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
* [ ] Design meeting ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
### Standard Library Contracts
* [ ] Standard Library Contracts (@celinval, @tautschnig)
* [ ] Writing new contracts ()
* [ ] Standard reviews ([libs](https://github.com/rust-lang/libs-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.

**Comment by celinval** [comment]
**Key developments:** We have written and verified around 220 safety contracts in the [verify-rust-std fork](https://github.com/model-checking/verify-rust-std). 3 out of 14 challenges have been solved. We have successfully integrated Kani in the repository CI, and we are working on the integration of 2 other verification tools: VeriFast and Goto-transcoder (ESBMC)

**Comment by nikomatsakis** [comment]
This is a continuing project goal, and the updates below this comment will be for the new period 2025h1

**Comment by celinval** [comment]
We have been able to merge the initial support for contracts in the Rust compiler under the `contracts` unstable feature. @tautschnig has created the first PR to incorporate contracts in the standard library and uncovered a few limitations that we've been working on.

**Comment by celinval** [comment]
We fixed issue https://github.com/rust-lang/rust/issues/136925 that was blocking contract annotations on constant functions, which unblocks the [initial PR to add some contract annotations in the standard library(https://github.com/rust-lang/rust/pull/136578). The PR currently triggers a CI failure which we are investigating.

**Comment by celinval** [comment]
Unfortunately, we didn't make much progress since April except for a very useful discussion during Rust all hands. A few notes can be found here: https://hackmd.io/@qnR1-HVLRx-dekU5dvtvkw/SyUuR6SZgx. We're still waiting for the design discussion meeting with the compiler team.

**Comment by celinval** [comment]
@dawidl022 is working as part of GSoC to improve contracts implementation under @tautschnig mentorship. Additionally, @tautschnig and @carolynzech are working on porting contracts from https://github.com/model-checking/verify-rust-std to the Rust repo.
