### ISSUE TITLE
test2 

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#59]
| Metadata | |
| --- | --- |
| Owner(s) | tmandry, nikomatsakis   |
| Teams | [lang], [libs], [libs-api] |
| Goal document | [2024h2/async.html](https://rust-lang.github.io/rust-project-goals/2024h2/async.html) |

## Summary

Over the next six months, we will deliver several critical async Rust building block features

* [resolve the "Send bound" problem](#stabilize-async-closures), which blocks the widespread usage of async functions in traits;
* [reorganize the async WG](#reorganize-the-async-wg), so that we can be better aligned and move more swiftly from here out;
* [stabilize async closures](#stabilize-async-closures), allowing for a much wider variety of async related APIs (async closures are implemented on nightly).

## Tasks and status

* [ ] Overall program management (tmandry, nikomatsakis)
* [ ] "Send bound" problem (nikomatsakis)
    * [x] Implementation (compiler-errors)
    * [x] Author RFC (nikomatsakis)
    * [ ] RFC decision ![Team][]
    * [ ] Stabilization decision ![Team][]
* [ ] Async WG reorganization (nikomatsakis)

| Subgoal                    | Owner(s) or team(s)         | Notes               |
| -------------------------- | --------------------------- | ------------------- |
| Overall program management | tmandry, nikomatsakis     |                     |
| "Send bound" problem       | nikomatsakis               |                     |
| ↳ ~~Implementation~~       | ~~compiler-errors~~        | ![Complete][]       |
| ↳ ~~Author RFC~~           | nikomatsakis               | ![Complete][]       |
| ↳ RFC decision             | ![Team][] [lang]            | ![Complete][]       |
| ↳ Stabilization decision   | ![Team][] [lang]            |                     |
| Async WG reorganization    | nikomatsakis               |                     |
| ↳ Author proposal          |                             |                     |
| ↳ Org decision             | ![Team][] [libs], [lang]    |                     |
| Async closures             | compiler-errors            |                     |
| ↳ ~~implementation~~       |                             | ![Complete][]       |
| ↳ Author RFC               |                             |                     |
| ↳ RFC decision             | ![Team][] [lang]            |                     |
| ↳ Design meeting           | ![Team][] [lang]            | 2 meetings expected |
| ↳ Author call for usage    | compiler-errors            |                     |
| ↳ Stabilization decision   | ![Team][] [lang]            |                     |
| Trait for async iteration  | eholk                      |                     |
| ↳ Author RFC               |                             |                     |
| ↳ RFC decision             | ![Team][] [libs-api] [lang] |                     |
| ↳ Design meeting           | ![Team][] [lang]            | 2 meetings expected |
| ↳ Implementation           |                             |                     |
| Dyn dispatch for AFIT      | spastorino                 |                     |
| ↳ Implementation           | spastorino                 |                     |
| ↳ Standard reviews         | tmandry                    |                     |
| Async drop experiments     | petrochenkov               |                     |
| ↳ ~~author MCP~~           |                             | ![Complete][]       |
| ↳ ~~MCP decision~~         | ~~[compiler]~~              | ![Complete][]       |
| ↳ Implementation work      |                             | ![Not funded][] (*) |
| ↳ Design meeting           | ![Team][] [lang]            | 2 meetings expected |
| ↳ Standard reviews         | ![Team][] [compiler]        |                     |

[Team]: https://img.shields.io/badge/Team%20ask-red
[Complete]: https://img.shields.io/badge/Complete-green
[Help wanted]: https://img.shields.io/badge/Help%20wanted-yellow

[lang]: XXX
[compiler]: XXX
[libs-api]: XXX

```[tasklist]
### Tasks
```
