### ISSUE TITLE
"Stabilizable" prototype for expanded const generics

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#63]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %BoxyUwU |
| Team(s)       | [lang](http://github.com/rust-lang/lang-team), [types](https://github.com/rust-lang/types-team) |
| Goal document | [2024h2/min_generic_const_arguments](https://rust-lang.github.io/rust-project-goals/2024h2/min_generic_const_arguments.html) |

## Summary

Experiment with a new `min_generic_const_args` implementation to address challenges found with the existing approach

## Tasks and status

* [ ] Discussion and moral support(![Team][] [lang](http://github.com/rust-lang/lang-team), [types](https://github.com/rust-lang/types-team))
* [ ] Implementation and mentoring(%BoxyUwu)
* [ ] Implementation(%camelid)
* [ ] Reviewer(%compiler-errors)
