### ISSUE TITLE
Administrator-provided reasons for yanked crates

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#67]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %hi-rustin |
| Team(s)       | [cargo](https://github.com/rust-lang/cargo), [crates-io](https://github.com/rust-lang/crates.io) |
| Goal document | [2024h2/yank-crates-with-a-reason](https://rust-lang.github.io/rust-project-goals/2024h2/yank-crates-with-a-reason.html) |

## Summary

Over the next 6 months, we will add support to the registry yank API for providing a reason when a crate is yanked. This reason can then be displayed to users. After this feature has been up and running for a while, we'll open it up to Cargo to support filling in the reason for yanking.

## Tasks and status

* [ ] Yank crates with a reason
  * [ ] Implementation (%hi-rustin)
  * [ ] Standard reviews ([crates-io](https://github.com/rust-lang/crates.io) ![Team][])
  * [ ] Try it out in crates.io ([crates-io](https://github.com/rust-lang/crates.io) ![Team][])
  * [ ] Author RFC (%hi-rustin)
  * [ ] Approve RFC ([cargo](https://github.com/rust-lang/cargo), [crates-io](https://github.com/rust-lang/crates.io) ![Team][])
  * [ ] Implementation in Cargo side (%hi-rustin)
  * [ ] Inside Rust blog post inviting feedback (%hi-rustin)
  * [ ] Stabilization decision ([cargo](https://github.com/rust-lang/cargo) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red
