### ISSUE TITLE
Assemble project goal slate

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#68]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %nikomatsakis |
| Team(s)       | [leadership-council](https://github.com/rust-lang/leadership-council) |
| Goal document | [2024h2/Project-goal-slate](https://rust-lang.github.io/rust-project-goals/2024h2/Project-goal-slate.html) |

## Summary

Run an experimental goal program during the second half of 2024

## Tasks and status

* [x] RFC decision ([leadership-council](https://github.com/rust-lang/leadership-council) ![Team][])
* [ ] Inside Rust blog post inviting feedback
* [ ] Top-level Rust blog post announcing result

[Team]: https://img.shields.io/badge/Team%20ask-red
