### ISSUE TITLE
Associated type position impl trait

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#69]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %oli-obk |
| Team(s)       | [lang](http://github.com/rust-lang/lang-team), [types](https://github.com/rust-lang/types-team) |
| Goal document | [2024h2/ATPIT](https://rust-lang.github.io/rust-project-goals/2024h2/ATPIT.html) |

## Summary

Stable support for `impl Trait` in the values of associated types (aka "associated type position impl trait" or ATPIT)

## Tasks and status

* [ ] Implementation (%oli-obk)
* [ ] FCP decisions ([types](https://github.com/rust-lang/types-team) ![Team][])
* [ ] Stabilization decision ([types](https://github.com/rust-lang/types-team), [lang](http://github.com/rust-lang/lang-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red
