### ISSUE TITLE
Begin resolving `cargo-semver-checks` blockers for merging into cargo

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#70]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %obi1kenobi |
| Team(s)       | [cargo](https://github.com/rust-lang/cargo) |
| Goal document | [2024h2/cargo-semver-checks](https://rust-lang.github.io/rust-project-goals/2024h2/cargo-semver-checks.html) |

## Summary

Design and implement `cargo-semver-checks` functionality that lies on the critical path for merging the tool into cargo itself.

## Tasks and status

* [ ] Implementation of cargo manifest linting + CLI (%obi1kenobi)
* [ ] Initial design for cross-crate checking (%obi1kenobi)
* [ ] Initial design for type-checking lints (%obi1kenobi)
* [ ] Discussion and moral support ([cargo](https://github.com/rust-lang/cargo) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red
