### ISSUE TITLE
Bring the Async Rust experience closer to parity with sync Rust

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#71]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %tmandry, %nikomatsakis |
| Team(s)       | [compiler](http://github.com/rust-lang/compiler-team), [lang](http://github.com/rust-lang/lang-team), [libs](https://github.com/rust-lang/libs-team), [libs-api](https://www.rust-lang.org/governance/teams) |
| Goal document | [2024h2/async](https://rust-lang.github.io/rust-project-goals/2024h2/async.html) |

## Summary

Over the next six months, we will deliver several critical async Rust building block features

* [resolve the "Send bound" problem](#stabilize-async-closures), which blocks the widespread usage of async functions in traits;
* [reorganize the async WG](#reorganize-the-async-wg), so that we can be better aligned and move more swiftly from here out;
* [stabilize async closures](#stabilize-async-closures), allowing for a much wider variety of async related APIs (async closures are implemented on nightly).

## Tasks and status

* [ ] Overall program management (%tmandry, %nikomatsakis)
* [ ] "Send bound" problem (%nikomatsakis)
  * [x] ~~Implementation~~ (%compiler-errors)
  * [x] ~~Author RFC~~ (%nikomatsakis)
  * [x] RFC decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])
  * [ ] Stabilization decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] Async WG reorganization (%nikomatsakis)
  * [ ] Author proposal
  * [ ] Org decision ([libs](https://github.com/rust-lang/libs-team), [lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] Async closures (%compiler-errors)
  * [x] ~~implementation~~
  * [ ] Author RFC
  * [ ] RFC decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])
  * [ ] Design meeting ([lang](http://github.com/rust-lang/lang-team) ![Team][])
  * [ ] Author call for usage (%compiler-errors)
  * [ ] Stabilization decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] Trait for async iteration (%eholk)
  * [ ] Author RFC
  * [ ] RFC decision ([libs-api](https://www.rust-lang.org/governance/teams), [lang](http://github.com/rust-lang/lang-team) ![Team][])
  * [ ] Design meeting ([lang](http://github.com/rust-lang/lang-team) ![Team][])
  * [ ] Implementation
* [ ] Dyn dispatch for AFIT (%spastorino)
  * [ ] Implementation (%spastorino)
  * [ ] Standard reviews (%tmandry)
* [ ] Async drop experiments (%petrochenkov)
  * [x] ~~author MCP~~
  * [x] ~~MCP decision~~ ()
  * [ ] Implementation work
  * [ ] Design meeting ([lang](http://github.com/rust-lang/lang-team) ![Team][])
  * [ ] Standard reviews ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red
