### ISSUE TITLE
Ergonomic ref-counting

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#80]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %jkelleyrtp |
| Team(s)       | [compiler](http://github.com/rust-lang/compiler-team), [lang](http://github.com/rust-lang/lang-team), [libs-api](https://www.rust-lang.org/governance/teams) |
| Goal document | [2024h2/ergonomic-rc](https://rust-lang.github.io/rust-project-goals/2024h2/ergonomic-rc.html) |

## Summary

Deliver nightly support some solution to reduce the ergonomic pain of working with ref-counted and cheaply cloneable types.

## Tasks and status

* [ ] Overall program management (%jkelleyrtp)
* [ ] Author RFC ()
* [ ] Design meeting ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] RFC decision ([lang](http://github.com/rust-lang/lang-team), [libs-api](https://www.rust-lang.org/governance/teams) ![Team][])
* [ ] Nightly implementation (%spastorino)
* [ ] Standard reviews ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
* [ ] Blog post on Inside Rust

[Team]: https://img.shields.io/badge/Team%20ask-red
