### ISSUE TITLE
Explore sandboxed build scripts

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#81]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %weihanglo |
| Team(s)       | [cargo](https://github.com/rust-lang/cargo), [compiler](http://github.com/rust-lang/compiler-team) |
| Goal document | [2024h2/sandboxed-build-script](https://rust-lang.github.io/rust-project-goals/2024h2/sandboxed-build-script.html) |

## Summary

Explore different strategies for sandboxing build script executions in Cargo.

## Tasks and status

* [ ] Design (%weihanglo)
* [ ] Discussion and moral support ([cargo](https://github.com/rust-lang/cargo) ![Team][])
* [ ] Security reviews ()
* [ ] Standard reviews ([cargo](https://github.com/rust-lang/cargo) ![Team][])
* [ ] Collaboration with GSoC proc-macro project ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
* [ ] Summary of experiments or RFC (%weihanglo)

[Team]: https://img.shields.io/badge/Team%20ask-red
