### ISSUE TITLE
Make Rustdoc Search easier to learn

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#85]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %notriddle |
| Team(s)       | [rustdoc](https://github.com/rust-lang/rust), [rustdoc-frontend](https://www.rust-lang.org/governance/teams) |
| Goal document | [2024h2/rustdoc-search](https://rust-lang.github.io/rust-project-goals/2024h2/rustdoc-search.html) |

## Summary

To make rustdoc's search engine more useful:

* Respond to some existing feedback.
* Write blog and forum posts to advertise these new features to the larger community, and seek out feedback to continue the progress.

## Tasks and status

* [ ] Discussion and moral support ([rustdoc](https://github.com/rust-lang/rust) ![Team][])
* [ ] Improve on any discovered weaknesses
  * [ ] Implementation: show type signature in SERP (%notriddle)
  * [ ] Implementation: tweak search algo (%notriddle)
  * [ ] Standard reviews ([rustdoc-frontend](https://www.rust-lang.org/governance/teams) ![Team][])
  * [ ] Design meeting ([rustdoc-frontend](https://www.rust-lang.org/governance/teams) ![Team][])
  * [ ] FCP review ([rustdoc-frontend](https://www.rust-lang.org/governance/teams) ![Team][])
* [ ] Feedback and testing
  * [ ] Inside Rust blog post inviting feedback

[Team]: https://img.shields.io/badge/Team%20ask-red
