### ISSUE TITLE
Next-generation trait solver

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#86]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %lcnr |
| Team(s)       | [rust-analyzer](https://github.com/rust-lang/rust-analyzer), [types](https://github.com/rust-lang/types-team) |
| Goal document | [2024h2/next-solver](https://rust-lang.github.io/rust-project-goals/2024h2/next-solver.html) |

## Summary

In the next 6 months we plan to extend the next-generation trait solver as follows:

- stabilize the use of the next-generation trait solver in coherence checking
- use the new implementation in rustdoc and lints where applicable 
- share the solver with rust-analyser
- successfully bootstrap the compiler when exclusively using the new implementation and run crater

## Tasks and status

* [ ] Discussion and moral support ([types](https://github.com/rust-lang/types-team) ![Team][])
* [ ] Stabilize next-generation solver in coherence
  * [ ] Implementation (%lcnr, %compiler-errors)
  * [ ] Standard reviews ([types](https://github.com/rust-lang/types-team) ![Team][])
  * [ ] Standard reviews ([rust-analyzer](https://github.com/rust-lang/rust-analyzer) ![Team][])
  * [ ] Stabilization decision ([types](https://github.com/rust-lang/types-team) ![Team][])
* [ ] Support next-generation solver in rust-analyzer
  * [ ] Implementation (library side) ()
  * [ ] Implementation (rust-analyzer side) ()
  * [ ] Standard reviews ([types](https://github.com/rust-lang/types-team) ![Team][])
  * [ ] Standard reviews ([rust-analyzer](https://github.com/rust-lang/rust-analyzer) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red
