### ISSUE TITLE
Patterns of empty types

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#88]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %Nadrieril |
| Team(s)       | [compiler](http://github.com/rust-lang/compiler-team), [lang](http://github.com/rust-lang/lang-team) |
| Goal document | [2024h2/Patterns-of-empty-types](https://rust-lang.github.io/rust-project-goals/2024h2/Patterns-of-empty-types.html) |

## Summary

Introduce an RFC for never patterns or other solutions for patterns involving uninhabited types.

## Tasks and status

* [ ] Author RFC (%Nadrieril)
* [ ] Implementation (%Nadrieril)
* [ ] Standard reviews ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
* [ ] Discussion and moral support ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] Author stabilization report ()

[Team]: https://img.shields.io/badge/Team%20ask-red
