### ISSUE TITLE
Resolve the biggest blockers to Linux building on stable Rust

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#89]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %nikomatsakis, %joshtriplett |
| Team(s)       | [compiler](http://github.com/rust-lang/compiler-team), [lang](http://github.com/rust-lang/lang-team), [libs-api](https://www.rust-lang.org/governance/teams) |
| Goal document | [2024h2/rfl_stable](https://rust-lang.github.io/rust-project-goals/2024h2/rfl_stable.html) |

## Summary

Stabilize unstable features required by Rust for Linux project including

* Stable support for RFL's customized ARC type
* Labeled goto in inline assembler and extended `offset_of!` support
* RFL on Rust CI
* Pointers to statics in constants

## Tasks and status

* [ ] Overall program management (%nikomatsakis, %joshtriplett)
* [ ] Arbitrary self types v2 (%adetaylor)
  * [x] ~~author RFC~~
  * [x] ~~RFC decision~~ ()
  * [ ] Implementation
  * [ ] Standard reviews ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
  * [ ] Stabilization decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] Derive smart pointer (%Darksonn)
  * [ ] ~~author RFC~~
  * [x] RFC decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])
  * [ ] Implementation (%dingxiangfei2009)
  * [ ] Author stabilization report (%dingxiangfei2009)
  * [ ] Stabilization decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] `asm_goto` (%nbdd0121)
  * [x] ~~implementation~~
  * [ ] Real-world usage in Linux kernel
  * [ ] Extend to cover full RFC
  * [ ] Author stabilization report
  * [ ] Stabilization decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])
* [ ] Extended `offset_of` syntax (%dingxiangfei2009)
  * [ ] Stabilization report
  * [ ] Stabilization decision ([libs-api](https://www.rust-lang.org/governance/teams) ![Team][])
* [ ] ~~RFL on Rust CI~~ (%Kobzol)
  * [x] ~~implementation~~
  * [ ] Policy draft
  * [ ] Policy decision ([compiler](http://github.com/rust-lang/compiler-team) ![Team][])
* [ ] Pointers to static in constants (%nikomatsakis)
  * [ ] Stabilization report
  * [ ] Stabilization decision ([lang](http://github.com/rust-lang/lang-team) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red
