### ISSUE TITLE
Rust 2024 Edition

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#90]
| Metadata      | |
| --------      | --- |
| Owner(s)      | %traviscross |
| Team(s)       | [lang](http://github.com/rust-lang/lang-team), [leadership-council](https://github.com/rust-lang/leadership-council), [types](https://github.com/rust-lang/types-team) |
| Goal document | [2024h2/Rust-2024-Edition](https://rust-lang.github.io/rust-project-goals/2024h2/Rust-2024-Edition.html) |

## Summary

Feature complete status for Rust 2024, with final release to occur in early 2025.

## Tasks and status

* [x] RFC decision ([leadership-council](https://github.com/rust-lang/leadership-council) ![Team][])
* [ ] Stabilization decision ([lang](http://github.com/rust-lang/lang-team), [types](https://github.com/rust-lang/types-team) ![Team][])
* [ ] Top-level Rust blog post

[Team]: https://img.shields.io/badge/Team%20ask-red
